# Generated by Django 4.2.13 on 2024-06-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiggSolucionesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('fecha_enviado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
