# Generated by Django 4.2.13 on 2024-06-30 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BiggSolucionesApp', '0002_contactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
