# Generated by Django 4.2.13 on 2024-06-30 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BiggSolucionesApp', '0003_delete_contactform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='mensaje',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='nombre',
        ),
    ]
